### PR TITLE
Ruby - OOP - Milestone: User interface

### PR DESCRIPTION
**Pull request by mke2111**
In this project, information from the users is prompted and the display slots of the game are shown to the users.

### CODE REVIEW

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

* [ ] the game informs player if the selected move is a winning move (without computing the winning move)
* [ ] the game informs player if the selected move is a draw move (without computing draw)

- [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))

use your code to make something like this

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

_**Note: please include the lib folder.**_


### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Review by Rhelli — CHANGES_REQUESTED** [review]
# Changes Required 🛑♻️

Hi team, excellent work on this milestone so far, I can see that you've managed to implement a lot of the procedural details here that will form the basis of your tic-tac-toe game so far. 

There are however a couple of additions that need to be made in order to advance to the next milestone and get this milestone approved. They shouldn't be too time consuming, but I'll detail them below.
 
*****

 ### **[Mandatory]** - **The game should display the board after the user has played their move.**

This doesn't require any logic at this point, so no need to worry about displaying an updated board, but do make sure to add in the appropriate call to display the board again following each players moves.

### **[Mandatory]** - The game should alert the players if a move has resulted in a draw.

Again, no logic is needed here, so in the same style that you have implemented your alert for a winner of the game, create a conditional to state if a draw has occurred between the players.

******

And that's it! Get those additional 2 statements added to your `main` file and we'll be able to get your project approved and you'll be onto the next milestone!

If you need any help, feel free to @ me here on Github or reach out to me over Slack. Good luck!

All the best,

💂🏽‍♂️ Rory

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
* [ ]  game displays board vertically for example
````ruby
[1,2,3]
[4,5,6]
[7,8,9]
`````
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by ghost — APPROVED** [review]
# Status: Project Approved

**Congratulations team and good luck with your next milestone 😃.**

**Pull request merged**
